### ISSUE TITLE
Add API upload endpoint

### ISSUE THREAD

**Issue by ohld** [morejust/store#3]
API endpoint should require secret token to be used. 
This upload endpoint should return the link to file.

**Comment by caffeinum** [comment]
Will frontend have this secret token?

**Comment by ohld** [comment]
We need somehow the ability to upload files via API, that returns the link to a file. It would be nice if this API will be secured (used some token) that can be set via Heroku environment variables (for example). @caffeinum

**Comment by ohld** [comment]
This API can become a huge point to use our tool.
