### ISSUE TITLE
Create Product Hunt page

### ISSUE THREAD

**Issue by ohld** [morejust/store#9]
Create PH page with links, videos, screenshots and descriptions.

@caffeinum, @kirillovmr please share here your Product Hunt links.

**Comment by kirillovmr** [comment]
https://www.producthunt.com/@kirillovmr

**Comment by caffeinum** [comment]
https://www.producthunt.com/@caffeinum

**Comment by ohld** [comment]
done: https://www.producthunt.com/posts/morejust-store
